version: '3.7'
networks:
  parking:

services:
  site:
    image: nginx:stable-alpine
    container_name: site
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
      - postgres
    networks:
      - parking

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    env_file:
      - src/.env
    networks:
      - parking


  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=parking_database
      - POSTGRES_USER=parking_root
      - POSTGRES_PASSWORD=Test12345!
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - parking

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - parking


  composer: 
    image: composer:2.1.6
    container_name: composer
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: /bin/sh -c "sleep 10 && composer install"
    networks: 
      - parking
